### PR TITLE
docs: fix flask_classy import

### PR DESCRIPTION
**Pull request by sboily**

### CODE REVIEW

**Comment by jirikuncar** [comment]
@sboily thank you for your contribution.

- [ ] Please add yourself to `AUTHORS`;
- [ ] Amend commit message to follow project style (`docs: fix flask_classy import`);
- [ ] Please reply if you agree to donate this (and any future) contributions to *Flask-Menu* package under the terms of the Revised BSD Licence.

**Comment by jirikuncar** [comment]
ping @sboily

**Comment by sboily** [comment]
Hello @jirikuncar,

sorry i'm busy ... I need to update this PR. Is it really important to have my self in AUTHORS for this small changes ?

I'm agree to donate my contributions under the terms of the revised BSD licence !

**Comment by jirikuncar** [comment]
@sboily thanks. I will cherry-pick and amend everything then. We needed mostly the agreement from your side. Cheers

**Comment by sboily** [comment]
Ok great ! Thank you for this great lib :)

**Pull request closed without merging**
